version: '3.7'
services:
  db:
    image: postgres:11.4
#    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - my_db:/var/lib/postgresql/data
    networks:
      - "my_spring"

  adminer:
    image: adminer:latest
    #     restart: always
    ports:
      - "8888:8080"
    networks:
      - "my_spring"

volumes:
  my_db:

networks:
  my_spring: